port: 4002
title: Fieldwork & Professional Practice
professor: Alain Paradis
email: paradia@algonquincollege.com
phone: +1 613-727-4723,5878
course-code: DSN1690
course-description: "Students work as junior designers in industry studios. Students practise the skills and techniques acquired throughout their studies and gain valuable experience in a variety of areas by working on projects for their chosen employer. Students are introduced to making contact with potential employers, presenting their work professionally, ensuring their personal brand reflects their strength as a designer, interviewing and ensuring they are ready for the job market. The course culminates in the preparation of the year-end grad show where industry representatives are invited to view student work, build relationships and provide valuable feedback."
logistics: "This is a multi-faceted course where students take the lead in raising funds, preparing for fieldwork and organizing their grad show. You will be organized in teams, each with a task described here. Each week, teams meet to move their responsibilites forward. Attendance & participation by each student is a requirement for passing the course."
prerequisits:
- DSN1545 Graphic Design 5
- DSN1668 Design Research 2
- DSN1677 Computer Graphics 5
- DSN1686 Web Development 5
- DSN1688 Motion Graphics 3
description: >- # this means to ignore newlines until "baseurl:"
  This is the Fieldwork & Professional Practice web site.
baseurl: ""
url: /fieldwork
twitter_username: alainparadis
github_username:  alainparadis

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
