port: 4002
title: Fieldwork & Professional Practice
email: paradia@algonquincollege.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the Fieldwork & Professional Practice web site.
baseurl: ""
twitter_username: alainparadis
github_username:  alainparadis

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
